Investigate castastrophic forgetting
SubstraFoundation/distributed-learning-contributivity pull request #183
Opened 2020-07-10 08:31 UTC by RomainGoussault

2020-07-10 09:30 UTC, bowni commented on constants.py
> +PATIENCE = 30  # patience for early stopping
:open_mouth:

2020-09-07 15:41 UTC, RomainGoussault commented
![image](https://user-images.githubusercontent.com/5354301/92403241-50d43f00-f131-11ea-9069-e181cdf04d98.png)
Hard to know why sometimes it works sometimes it does not. Nothing in the logs.
I am running more experients with less parameters variation and more repeats.

2020-09-22 09:49 UTC, RomainGoussault commented
The notebook should be put in the saved_experiments folder. Also the data should be pushed to the repo.

2020-09-22 16:27 UTC, arthurPignet commented
> The notebook should be put in the saved_experiments folder. Also the data should be pushed to the repo.

What do you mean by the data should be pushed to the repo ? Not the dataset ?

2020-09-22 16:35 UTC, arthurPignet reviewed
Really interesting 
The notebook works with the main file, in the old functionnement of the library, don't you think it could be interesting to use the new mplc package ? 
with a list of the scenario tested, etc
However it is not mandatory for merging

2020-09-22 16:36 UTC, arthurPignet approved these changes

2020-09-22 16:49 UTC, arthurPignet requested changes
On the notebook : 
Maybe you could add few sentences on the choice of your parameters. Why one category per partner, why these tests on the minibatch parameter.

Why do you print the 40 graphics ? And only for the scenario with one minibatch ?

What you are naming local_validation_score is computed on the global validation set, with the local model, you can have a confusion here. (Which is important, because technically with catastrophic forgetting, the local model overfit on the local train set. Each partner got only one class, so the accuracy on the the local validation dataset would be near 100%)

2020-09-30 09:53 UTC, bowni commented
@RomainGoussault are @arthurPignet comments relevant from your perspective? Can you indicate if you plan to keep making updates to this PR or if we should merge it now?

2020-10-05 16:12 UTC, RomainGoussault commented
> > The notebook should be put in the saved_experiments folder. Also the data should be pushed to the repo.
> 
> What do you mean by the data should be pushed to the repo ? Not the dataset ?

I meant, the results files should be pushed to the repos. Actually I did pushed the results.csv but I forget to push the individual results. (When we resolved this https://github.com/SubstraFoundation/distributed-learning-contributivity/issues/174, life will be easier :))

2020-10-05 16:41 UTC, RomainGoussault commented
@arthurPignet you are right on the local_validation_score, it is global_actually. (we should rename the array `score_matrix_per_partner`, it's a bit confusing).
And as you said, it will be nice to have the local validation score, but I think we don't have it.

2020-10-05 16:44 UTC, RomainGoussault commented
@bowni yes I still plan to improve the notebooks, sorry for the delay !.
And Thanks @arthurPignet for the very relevant comments !

The next steps are:
* pushing all the results (all the folders to get the loss data)
* see if we can get the local validation score but I think we can not.

2020-10-06 07:56 UTC, bowni approved these changes

2020-10-27 17:07 UTC, arthurPignet approved these changes

2020-10-28 08:21 UTC, merged