Makefile
SubstraFoundation/distributed-learning-contributivity pull request #333
Opened 2021-04-01 07:30 UTC by natct10

2021-04-01 12:47 UTC, bowni requested changes
Cool thing in principle. But I would have a couple remarks:

1. Could we remove the black formatter? I really don't like the syntax it gives, it makes code files difficult to read

1. As discussed this morning, I am not too sure about end-to-end tests on this one, it might take a while, and become useless because of that. I think flake + unit tests would be a good combo, both handy and useful

2021-04-02 12:15 UTC, natct10 commented
> Cool thing in principle. But I would have a couple remarks:
> 
>     1. Could we remove the black formatter? I really don't like the syntax it gives, it makes code files difficult to read

Black is a great tool. And you don't have to accept all, `git add -p` is useful in this regard.

>     2. As discussed this morning, I am not too sure about end-to-end tests on this one, it might take a while, and become useless because of that. I think flake + unit tests would be a good combo, both handy and useful

This part is refined in this PR: https://github.com/SubstraFoundation/distributed-learning-contributivity/pull/336/files. The idea was -even if the command takes a long time to be executed- to have an alias to run it.

Let me know

2021-04-06 09:25 UTC, bowni approved these changes
LGTM 👍 @natct10

2021-04-06 12:15 UTC, natct10 commented
Closing as it is included in [336](https://github.com/SubstraFoundation/distributed-learning-contributivity/pull/336/files)

2021-04-06 12:15 UTC, closed without merging