Fix config file errors
SubstraFoundation/distributed-learning-contributivity pull request #360
Opened 2021-11-10 10:14 UTC by celinejacques

- Update variable names (_dataset_name_ in _dataset_, _aggregation_weighting_ in _aggregation_, _methods_ in _contributivity_methods_)
- Change split method from list to string for basic methods (eg. ['basic', 'stratified'] in 'stratified')
- For aggregation methods, change _data_volume_ in _data-volume_
- Update README and documentation

2021-11-10 15:57 UTC, bowni requested changes

2021-11-15 08:20 UTC, bowni commented on mplc/doc/documentation.md
> +- `aggregation`: `'uniform'` (default), `'data_volume'` or `'local_score'`
Fixed

2021-11-15 08:23 UTC, bowni commented on config.yml
> +     - [ 'advanced', [ [ 4, 'shared' ], [ 6, 'shared' ], [ 4, 'specific' ] ] ]
Added

2021-11-15 08:24 UTC, bowni commented
@celinejacques I committed fixes to the above 2 remarks - can you please review and test it?

2021-11-16 10:07 UTC, bowni approved these changes

2021-11-17 09:47 UTC, arthurPignet approved these changes

2021-11-17 10:38 UTC, merged